### ISSUE TITLE
Make exercise info togglable

### ISSUE THREAD

**Issue by AlexJanow** [AlexJanow/WeightMate#17]
As a user

I want to have toggleable info container

so that I can have a better overview of the app

## Description
make exercise info toggleable
## Acceptance criteria
single exercise should be looking similar to each other and info should be toggleable

## Complexity
small

## Tasks

- [x] search for spoiler feature
- [x] implement feature
- [x] decide how to manage empty container
- [x] test different exercises
