### ISSUE TITLE
Make possible to add weight and repetitions to single exercise

### ISSUE THREAD

**Issue by AlexJanow** [AlexJanow/WeightMate#18]
As a user

I want to put in the work i've done

so that I can keep track of my progress

## Description
add form to single exercise
## Acceptance criteria
when exercise is chosen, there should be the possibility to input weight and repetitions, which get saved in states as objects for this exercise id

## Complexity
big

## Tasks

- [x] choose whether to stay on exercise info screen for input or search -> single exercise -> choose-> back to screen for input
- [x]  save input to exercise id
- [x]  console.log example data
