### ISSUE TITLE
Save exercise input to localStorage

### ISSUE THREAD

**Issue by AlexJanow** [AlexJanow/WeightMate#19]
As a developer

I want to save the data to localStorage

so that I can display the progress

## Description
save the data objects of the states in localStorage
## Acceptance criteria
data should stay after page reload

## Complexity
medium

## Tasks

- [x] choose how to store
- [x] store to localStorage
- [x] check if it works
