### ISSUE TITLE
Display Training Input

### ISSUE THREAD

**Issue by AlexJanow** [AlexJanow/WeightMate#32]
As a user

I want the training input displayed

so that I can see what I've done

## Description
make Training input visible below button and add to array
## Acceptance criteria
should be visible below button

## Complexity
medium

## Tasks

- [x] display state input
- [x] save to array to display multiple inputs (sets)
- [x] display multiple sets
