### ISSUE TITLE
Adding Chart.js to exerciseId

### ISSUE THREAD

**Issue by AlexJanow** [AlexJanow/WeightMate#39]
As a user
I want a chart for the exercise progress

so that I can see my progress

## Description
Calculate meaningfull weight and display it in Chart.js
## Acceptance criteria
Added sets should display progress in chart

## Complexity
big

## Tasks

- [ ] find the right formula
- [ ] add the data to chart.js
- [ ] display sample data
- [ ] choose where to put chart
