### ISSUE TITLE
Strength Formula

### ISSUE THREAD

**Issue by AlexJanow** [AlexJanow/WeightMate#40]
As a User
I want to calculate my strength

so that I can see my progress

## Description
Add Brzycki and Epley formula for calculating One-rep-max
## Acceptance criteria
Given different weight and repetition inputs the 1RM should be displayed in a logical way.
## Complexity
medium

## Tasks

- [x] understand formulas
- [x] write algorithm 
- [x] test if Brzycki formula makes sense for under 8 repetitions
- [x] test if Epley formula makes sense for over 10 repetitions
- [x] if above test positive, test linear interpolation of Brzycki and Epley (9 repetitions is 50-50)
- [x] test multiple sample exercise inputs
