### ISSUE TITLE
Progress Feedback

### ISSUE THREAD

**Issue by AlexJanow** [AlexJanow/WeightMate#42]
As a user

I want my a visual effect to show my progress

so that I can be motivated

## Description
Display change in performance
## Acceptance criteria
If weight is new personal best of exercise, display "new PR" with appropiate color.
(maybe confetti animation)

## Complexity
medium

## Tasks

- [ ] discuss where to display
- [ ] implement display of pr
- [ ] test
- [ ] optional confetti animation
