### ISSUE TITLE
Create Bodyweight Page

### ISSUE THREAD

**Issue by AlexJanow** [AlexJanow/WeightMate#5]
As a developer

I want to display the user an input at the bodyweight page

so that he can input his bodyweight and save it to localStorage.

## Description
Make input on bodyweight page and save the input in local storage with the date of the input.

## Acceptance criteria

The input should be saved into localStorage with the date of the input (day only)

## Complexity
medium

## Tasks

- [x] add container
- [x] add date DD/MM/YYYY
- [x] add input field with __kg 
- [x] add "+"-Button
- [x] add functionality to save the input to localStorage by clicking on "+"-Button
