### ISSUE TITLE
Add Footer with Material UI

### ISSUE THREAD

**Issue by AlexJanow** [AlexJanow/WeightMate#8]
As a developer

I want to display clean UI

so that the user can navigate the app

## Description
Create Footer navigation with Material UI
##Acceptance criteria
Must be clean looking and working navigation

## Complexity
small

## Tasks

- [x] install Material UI
- [x] Make Navbar Skeleton
- [x] Add Icons
- [x] Link Navigation

## Bug

- [x] Fix: Navbar is moving when Home is clicked
