### ISSUE TITLE
Create Mockup Chart

### ISSUE THREAD

**Issue by AlexJanow** [AlexJanow/WeightMate#9]
As a developer

I want to try out chartJS

so that I can understand it better for futher development

## Description
create mockup charts

## Acceptance criteria
Example data should be displayed as chart

## Complexity
small

## Tasks

- [x] install chartjs
- [x] make chart component for bodyweight
- [x] use mockup data and implement it in chart
- [x] display component in home-page
